export const authCopy = {
  common: {
    appName: 'JDM Experience',
    continue: 'Continuar',
    submit: 'Enviar',
    cancel: 'Cancelar',
    back: 'Voltar',
    or: 'ou',
    loading: 'Carregando…',
    logout: 'Sair',
  },
  errors: {
    network: 'Sem conexão. Tente novamente.',
    unknown: 'Algo deu errado.',
    invalidCredentials: 'E-mail ou senha inválidos.',
    emailExists: 'Esse e-mail já está cadastrado.',
    emailNotVerified: 'Confirme seu e-mail antes de entrar.',
    weakPassword: 'Use pelo menos 10 caracteres.',
    rateLimited: 'Muitas tentativas. Aguarde um instante.',
    invalidLink: 'Link inválido.',
  },
  login: {
    title: 'Entrar',
    tagline: 'BEM-VINDO À CENA.',
    email: 'E-mail',
    password: 'Senha',
    submit: 'Entrar',
    forgot: 'Esqueci minha senha',
    noAccount: 'Ainda não tenho conta',
    noAccountPrefix: 'Ainda não está na cena? ',
    createAccount: 'Criar conta',
    withGoogle: 'Entrar com Google',
    withApple: 'Entrar com Apple',
  },
  signup: {
    title: 'Criar conta',
    name: 'Nome',
    email: 'E-mail',
    password: 'Senha (mín. 10 caracteres)',
    submit: 'Criar conta',
    haveAccount: 'Já tenho conta',
    agree: 'Ao continuar você concorda com os Termos e a Política de Privacidade.',
  },
  forgot: {
    title: 'Recuperar senha',
    email: 'E-mail cadastrado',
    submit: 'Enviar link',
    sent: 'Se o e-mail existir, enviaremos um link em instantes.',
  },
  reset: {
    title: 'Nova senha',
    password: 'Nova senha (mín. 10 caracteres)',
    submit: 'Atualizar senha',
    done: 'Senha atualizada.',
  },
  verify: {
    loading: 'Confirmando seu e-mail...',
    done: 'E-mail confirmado. Redirecionando...',
  },
  verifyPending: {
    title: 'Confirme seu e-mail',
    body: (email: string) => `Enviamos um link para ${email}. Toque no link para ativar sua conta.`,
    bodyNoEmail: 'Enviamos um link para o seu e-mail. Toque no link para ativar sua conta.',
    resend: 'Reenviar e-mail',
    resent: 'Enviamos novamente. Verifique sua caixa de entrada.',
    checkAgain: 'Já confirmei',
  },
  welcome: {
    greeting: (name: string) => `Olá, ${name}`,
    fallbackName: 'piloto',
    body: 'Você está dentro. Em breve, eventos e ingressos.',
  },
};
