export const authCopy = {
  common: {
    appName: 'JDM Experience',
    continue: 'Continuar',
    submit: 'Enviar',
    cancel: 'Cancelar',
    back: 'Voltar',
    or: 'ou',
    loading: 'Carregando…',
    logout: 'Sair',
  },
  errors: {
    network: 'Sem conexão. Tente novamente.',
    unknown: 'Algo deu errado.',
    invalidCredentials: 'E-mail ou senha inválidos.',
    emailExists: 'Esse e-mail já está cadastrado.',
    emailNotVerified: 'Confirme seu e-mail antes de entrar.',
    weakPassword: 'Use pelo menos 10 caracteres.',
    rateLimited: 'Muitas tentativas. Aguarde um instante.',
    invalidLink: 'Link inválido.',
    accountDisabled: 'Sua conta foi desabilitada. Contate o suporte.',
  },
  login: {
    title: 'Entrar',
    tagline: 'Bem-vindo à cena.',
    email: 'E-mail',
    emailPlaceholder: 'voce@email.com',
    password: 'Senha',
    passwordPlaceholder: '',
    submit: 'Entrar',
    forgot: 'Esqueci minha senha',
    noAccount: 'Ainda não tenho conta',
    noAccountPrefix: 'Ainda não está na cena? ',
    createAccount: 'Criar conta',
    withGoogle: 'Entrar com Google',
    withApple: 'Entrar com Apple',
  },
  signup: {
    eyebrow: 'Cadastro',
    title: 'Entre na cena',
    name: 'Nome',
    namePlaceholder: 'Seu nome completo',
    email: 'E-mail',
    emailPlaceholder: 'voce@email.com',
    password: 'Senha',
    passwordHint: 'Mínimo 10 caracteres.',
    submit: 'Criar conta',
    termsAccept: 'Aceito os ',
    termsLink: 'Termos',
    termsAnd: ' e a ',
    privacyLink: 'Política de privacidade',
    termsRequired: 'Aceite os termos para continuar.',
    haveAccountPrefix: 'Já tem conta? ',
    haveAccountLink: 'Entrar',
  },
  forgot: {
    title: 'Recuperar senha',
    subtitle: 'Digita o e-mail da sua conta e a gente manda um link pra você redefinir a senha.',
    email: 'E-mail',
    emailPlaceholder: 'voce@email.com',
    submit: 'Enviar link',
    sent: 'Se o e-mail existir, enviaremos um link em instantes.',
    successTitle: 'Confira seu e-mail',
    successBody: (email: string) =>
      `Mandamos o link para ${email}. Toque no link pra redefinir a senha.`,
    resend: 'Reenviar',
    resendIn: (s: number) => `Reenviar em ${s}s`,
    notFound: 'E-mail não encontrado.',
    back: 'Voltar pro login',
  },
  reset: {
    title: 'Nova senha',
    subtitle: 'Cria uma senha nova pra sua conta. Mínimo 10 caracteres.',
    password: 'Senha nova',
    confirm: 'Confirma a senha',
    submit: 'Alterar senha',
    done: 'Senha atualizada.',
    mismatch: 'As senhas não coincidem.',
    invalidLinkTitle: 'Link expirado',
    invalidLinkBody: 'Esse link não é mais válido. Pede um novo pra recuperar a senha.',
    requestNewLink: 'Pedir outro link',
    showPassword: 'Mostrar senha',
    hidePassword: 'Esconder senha',
    strengthLabel: 'Força',
    strengthWeak: 'Fraca',
    strengthMedium: 'Média',
    strengthStrong: 'Forte',
  },
  verify: {
    loading: 'Confirmando seu e-mail...',
    done: 'E-mail confirmado. Redirecionando...',
  },
  verifyPending: {
    title: 'Confirme seu e-mail',
    body: (email: string) => `Enviamos um link para ${email}. Toque no link para ativar sua conta.`,
    bodyNoEmail: 'Enviamos um link para o seu e-mail. Toque no link para ativar sua conta.',
    resend: 'Reenviar e-mail',
    resent: 'Enviamos novamente. Verifique sua caixa de entrada.',
    checkAgain: 'Já confirmei',
  },
  welcome: {
    greeting: (name: string) => `Olá, ${name}`,
    fallbackName: 'piloto',
    body: 'Você está dentro. Em breve, eventos e ingressos.',
  },
};
