export const cartCopy = {
  title: 'Carrinho',
  empty: 'Seu carrinho está vazio.',
  emptySub: 'Explore os eventos e produtos e adicione seus itens.',
  browseEvents: 'Ver eventos',
  item: {
    ticket: 'Ingresso',
    product: 'Produto',
    extras: 'Extras',
    remove: 'Remover',
    quantity: (n: number) => `${n}x`,
    tapExtras: 'Toque para gerenciar extras',
    viewProduct: 'Toque para ver o produto',
    selectCar: 'Selecionar carro',
    changeCar: 'Trocar carro',
    carRequired: 'Carro obrigatório',
    plate: (p: string) => `Placa ${p}`,
    shipping: 'Entrega',
    pickup: 'Retirada',
  },
  drawer: {
    title: 'Extras',
    empty: 'Nenhum extra disponível para este evento.',
    add: 'Adicionar',
    remove: 'Remover',
    extrasTotal: 'Subtotal extras',
    loading: 'Carregando extras...',
    error: 'Erro ao carregar extras.',
  },
  totals: {
    tickets: 'Ingressos',
    products: 'Produtos',
    shipping: 'Entrega',
    extras: 'Extras',
    discount: 'Desconto',
    total: 'Total',
  },
  sections: {
    tickets: 'Ingressos',
    products: 'Produtos',
  },
  actions: {
    addToCart: 'Adicionar ao carrinho',
    adding: 'Adicionando...',
    added: 'Adicionado ao carrinho!',
    checkout: 'Finalizar compra',
    pay: 'Pagar',
    paying: 'Processando...',
    clear: 'Limpar carrinho',
    clearConfirm: 'Tem certeza que deseja limpar o carrinho?',
    clearYes: 'Limpar',
    clearNo: 'Cancelar',
    close: 'Fechar',
  },
  payment: {
    method: 'Forma de pagamento',
    card: 'Cartão',
    pix: 'Pix',
  },
  shipping: {
    title: 'Endereço de entrega',
    placeholder: 'Selecione o endereço',
    loading: 'Carregando endereços...',
    add: 'Adicionar',
    addNew: 'Adicionar novo...',
    retry: 'Tentar novamente',
    defaultBadge: 'Padrão',
    blocked: 'Selecione um endereço de entrega para pagar.',
  },
  pickup: {
    title: 'Retirada no evento',
    placeholder: 'Selecione o evento',
    loading: 'Carregando eventos elegíveis...',
    retry: 'Tentar novamente',
    disabled: 'A retirada no evento está desativada no momento.',
    noEligible: 'Adicione um ingresso válido do mesmo evento para retirar seus produtos.',
    blocked: 'Selecione o evento da retirada para pagar.',
    ownedTicket: 'Você já tem um ingresso válido para este evento.',
    cartTicket: 'Esse ingresso será criado junto com este pedido.',
    ownedBadge: 'Ingresso no app',
    cartBadge: 'Ingresso no pedido',
  },
  errors: {
    load: 'Não foi possível carregar o carrinho.',
    add: 'Erro ao adicionar item ao carrinho.',
    remove: 'Erro ao remover item do carrinho.',
    clear: 'Erro ao limpar o carrinho.',
    checkout: 'Erro ao iniciar o pagamento.',
    retry: 'Tentar novamente',
    maxTicketsExceeded: (max: number) =>
      `Você já atingiu o limite de ${max} ingresso${max === 1 ? '' : 's'} por pessoa neste evento.`,
    tierSoldOut: 'Ingresso esgotado.',
    salesNotOpen: 'As vendas ainda não começaram para este ingresso.',
    salesClosed: 'As vendas para este ingresso foram encerradas.',
    extraSoldOut: 'Um dos extras selecionados está esgotado.',
    variantSoldOut: 'Este produto está esgotado.',
  },
  badge: (n: number) => (n > 9 ? '9+' : `${n}`),
  stockWarning: {
    tier_low_stock: 'Poucas unidades restantes',
    extra_low_stock: 'Poucas unidades restantes',
    tier_sold_out: 'Esgotado',
    extra_sold_out: 'Extra esgotado',
  },
  evicted: {
    title: 'Itens removidos',
    event_unpublished: 'Evento não está mais disponível',
    event_cancelled: 'Evento cancelado',
    tier_removed: 'Ingresso não está mais disponível',
    extra_removed: 'Extra não está mais disponível',
    extra_sold_out: 'Extra esgotado',
  },
};
