export const cartCopy = {
  title: 'Carrinho',
  empty: 'Seu carrinho está vazio.',
  emptySub: 'Explore os eventos e adicione ingressos.',
  browseEvents: 'Ver eventos',
  item: {
    ticket: 'Ingresso',
    extras: 'Extras',
    remove: 'Remover',
    quantity: (n: number) => `${n}x`,
    tapExtras: 'Toque para gerenciar extras',
    selectCar: 'Selecionar carro',
    changeCar: 'Trocar carro',
    carRequired: 'Carro obrigatório',
    plate: (p: string) => `Placa ${p}`,
  },
  drawer: {
    title: 'Extras',
    empty: 'Nenhum extra disponível para este evento.',
    add: 'Adicionar',
    remove: 'Remover',
    extrasTotal: 'Subtotal extras',
    loading: 'Carregando extras...',
    error: 'Erro ao carregar extras.',
  },
  totals: {
    tickets: 'Ingressos',
    extras: 'Extras',
    discount: 'Desconto',
    total: 'Total',
  },
  actions: {
    addToCart: 'Adicionar ao carrinho',
    adding: 'Adicionando...',
    added: 'Adicionado ao carrinho!',
    checkout: 'Finalizar compra',
    pay: 'Pagar',
    paying: 'Processando...',
    clear: 'Limpar carrinho',
    clearConfirm: 'Tem certeza que deseja limpar o carrinho?',
    clearYes: 'Limpar',
    clearNo: 'Cancelar',
    close: 'Fechar',
  },
  payment: {
    method: 'Forma de pagamento',
    card: 'Cartão',
    pix: 'Pix',
  },
  errors: {
    load: 'Não foi possível carregar o carrinho.',
    add: 'Erro ao adicionar item ao carrinho.',
    remove: 'Erro ao remover item do carrinho.',
    clear: 'Erro ao limpar o carrinho.',
    checkout: 'Erro ao iniciar o pagamento.',
    retry: 'Tentar novamente',
  },
  badge: (n: number) => (n > 9 ? '9+' : `${n}`),
  stockWarning: {
    tier_low_stock: 'Poucas unidades restantes',
    extra_low_stock: 'Poucas unidades restantes',
    tier_sold_out: 'Esgotado',
    extra_sold_out: 'Extra esgotado',
  },
  evicted: {
    title: 'Itens removidos',
    event_unpublished: 'Evento não está mais disponível',
    event_cancelled: 'Evento cancelado',
    tier_removed: 'Ingresso não está mais disponível',
    extra_removed: 'Extra não está mais disponível',
    extra_sold_out: 'Extra esgotado',
  },
};
