export const ordersCopy = {
  title: 'Meus pedidos',
  empty: 'Você ainda não tem pedidos da loja.',
  emptySub: 'Quando um produto entrar no seu carrinho, ele aparece aqui.',
  retry: 'Tentar novamente',
  loadFailed: 'Não foi possível carregar seus pedidos.',
  paymentStatus: {
    pending: 'Pagamento pendente',
    paid: 'Pago',
    failed: 'Falhou',
    refunded: 'Reembolsado',
    expired: 'Expirado',
    cancelled: 'Cancelado',
  },
  fulfillmentStatus: {
    unfulfilled: 'Separando',
    packed: 'Embalado',
    shipped: 'Enviado',
    delivered: 'Entregue',
    pickup_ready: 'Pronto para retirada',
    picked_up: 'Retirado',
    cancelled: 'Cancelado',
  },
  fulfillmentMethod: {
    ship: 'Entrega',
    pickup: 'Retirada',
  },
  orderKind: {
    ticket: 'Evento',
    extras_only: 'Extras',
    product: 'Loja',
    mixed: 'Evento + loja',
  },
  summary: {
    orderId: 'Pedido',
    shipping: 'Frete',
    eventDate: 'Evento',
    orderDate: 'Pedido em',
    total: 'Total',
    separator: '•',
  },
  actions: {
    cancel: 'Cancelar pedido',
    keep: 'Manter pedido',
    confirm: 'Confirmar cancelamento',
    cancelling: 'Cancelando...',
  },
  cancelModal: {
    title: 'Cancelar pedido pendente?',
    body: 'O pedido será encerrado e liberaremos a reserva dos itens. Esta ação não pode ser desfeita.',
    success: 'Pedido cancelado.',
    genericError: 'Não foi possível cancelar o pedido.',
    conflictError: 'Este pedido não está mais pendente.',
  },
  viewTicket: 'Ver ingresso',
  viewTickets: 'Ver ingressos',
  pay: 'Pagar',
  payError: 'Não foi possível retomar o pagamento.',
  payErrorBody: 'Tente novamente ou entre em contato com o suporte.',
};
