export const pixCopy = {
  title: 'Pagamento Pix',
  scanQr: 'Escaneie o QR Code com seu app bancário',
  orCopy: 'Ou copie o código',
  copyButton: 'Copiar código',
  copied: 'Copiado!',
  expiresIn: 'Expira em',
  expired: 'Código expirado',
  expiredSub: 'O tempo para pagamento esgotou. Tente novamente.',
  paid: 'Pagamento confirmado!',
  paidSub: 'Seu pedido está pronto.',
  viewTicket: 'Ver ingresso',
  failed: 'Pagamento não processado.',
  failedSub: 'Tente novamente ou escolha outro método.',
  tryAgain: 'Tentar novamente',
  errorPolling: 'Erro ao verificar pagamento.',
  errorReconnect: 'Reconectar',
  waiting: 'Aguardando pagamento...',
  amount: 'Valor',
};
