export const profileCopy = {
  profile: {
    title: 'Perfil',
    edit: 'Editar',
    save: 'Salvar',
    cancel: 'Cancelar',
    nameLabel: 'Nome',
    bioLabel: 'Bio',
    cityLabel: 'Cidade',
    stateLabel: 'Estado (UF)',
    avatarChange: 'Alterar foto',
    avatarUploading: 'Enviando foto…',
    saved: 'Perfil atualizado.',
    saveFailed: 'Não foi possível salvar.',
  },
  garage: {
    title: 'Garagem',
    empty: 'Você ainda não cadastrou carros.',
    add: 'Adicionar carro',
    makeLabel: 'Marca',
    modelLabel: 'Modelo',
    yearLabel: 'Ano',
    nicknameLabel: 'Apelido (opcional)',
    save: 'Salvar',
    saved: 'Carro atualizado.',
    saveFailed: 'Não foi possível salvar o carro.',
    delete: 'Excluir',
    deleteConfirm: 'Remover este carro?',
    addPhoto: 'Adicionar foto',
    replacePhoto: 'Trocar',
    photoUploading: 'Enviando foto…',
    removePhoto: 'Remover',
    removePhotoConfirm: 'Remover foto deste carro?',
  },
  errors: {
    network: 'Sem conexão. Tente novamente.',
    unknown: 'Algo deu errado.',
    imageTooLarge: 'Imagem acima de 10 MB.',
    imagePicker: 'Não foi possível abrir a galeria.',
  },
};
