export const profileCopy = {
  profile: {
    title: 'Perfil',
    edit: 'Editar',
    editDetails: 'Editar dados',
    save: 'Salvar',
    cancel: 'Cancelar',
    nameLabel: 'Nome',
    bioLabel: 'Bio',
    bioHint: 'Não inclua documentos, senhas ou informações bancárias.',
    cityLabel: 'Cidade',
    stateLabel: 'Estado (UF)',
    avatarChange: 'Alterar foto',
    avatarUploading: 'Enviando foto…',
    saved: 'Perfil atualizado.',
    saveFailed: 'Não foi possível salvar.',
    loadFailed: 'Não foi possível carregar o perfil.',
  },
  menu: {
    subtitle: 'Gerencie seus dados, endereços e sua garagem.',
    editHint: 'Atualize nome, bio e localização',
    pushPreferences: 'Notificações de marketing',
    pushPreferencesHint: 'Escolha se quer receber campanhas e novidades',
    orders: 'Meus pedidos',
    ordersHint: 'Acompanhe compras da loja e pedidos mistos',
    shipping: 'Endereços',
    shippingHint: 'Cadastre e edite seus endereços de entrega',
    garage: 'Garagem',
    garageHint: 'Veja e edite seus carros',
    support: 'Suporte',
    supportHint: 'Abra um chamado ou acompanhe seus tickets',
    logoutHint: 'Encerrar sessão neste aparelho',
  },
  consent: {
    title: 'Comunicações de marketing',
    body: 'A JDM Experience gostaria de enviar notificações sobre eventos, promoções e novidades. Você pode mudar isso a qualquer momento em Configurações → Notificações.',
    acceptLabel: 'Aceitar',
    declineLabel: 'Agora não',
    channel: 'Push marketing',
  },
  pushPreferences: {
    title: 'Notificações de marketing',
    description: 'Receba campanhas, novidades e avisos promocionais da JDM Experience no app.',
    transactionalNotice:
      'Avisos transacionais, como confirmação de ingresso e lembretes de evento, continuam separados e ativos.',
    toggleLabel: 'Receber campanhas e novidades por push',
    save: 'Salvar preferência',
    enabled: 'Marketing por push ativado.',
    disabled: 'Marketing por push desativado.',
    loadFailed: 'Não foi possível carregar sua preferência.',
    saveFailed: 'Não foi possível salvar sua preferência.',
  },
  shipping: {
    title: 'Endereços',
    newTitle: 'Novo endereço',
    empty: 'Você ainda não cadastrou endereços de entrega.',
    add: 'Adicionar endereço',
    retry: 'Tentar novamente',
    recipientNameLabel: 'Nome do destinatário',
    phoneLabel: 'Telefone',
    postalCodeLabel: 'CEP',
    streetLabel: 'Rua',
    numberLabel: 'Número',
    complementLabel: 'Complemento (opcional)',
    neighborhoodLabel: 'Bairro',
    cityLabel: 'Cidade',
    stateCodeLabel: 'Estado (UF)',
    cepLookupNotFound: 'CEP não encontrado. Preencha o endereço manualmente.',
    cepLookupError: 'Erro ao buscar CEP. Verifique sua conexão.',
    defaultLabel: 'Usar como endereço padrão',
    defaultBadge: 'Padrão',
    save: 'Salvar',
    saved: 'Endereço atualizado.',
    saveFailed: 'Não foi possível salvar o endereço.',
    loadFailed: 'Não foi possível carregar os endereços.',
    delete: 'Excluir',
    deleting: 'Excluindo...',
    deleteConfirm: 'Remover este endereço?',
    openDetailsHint: 'Abrir endereço',
  },
  garage: {
    title: 'Garagem',
    newTitle: 'Novo Carro',
    empty: 'Você ainda não cadastrou carros.',
    add: 'Adicionar carro',
    makeLabel: 'Marca',
    modelLabel: 'Modelo',
    yearLabel: 'Ano',
    nicknameLabel: 'Apelido (opcional)',
    save: 'Salvar',
    saved: 'Carro atualizado.',
    saveFailed: 'Não foi possível salvar o carro.',
    delete: 'Excluir',
    deleteConfirm: 'Remover este carro?',
    addPhoto: 'Adicionar foto',
    replacePhoto: 'Trocar',
    photoUploading: 'Enviando foto…',
    removePhoto: 'Remover',
    removePhotoConfirm: 'Remover foto deste carro?',
  },
  support: {
    title: 'Suporte',
    explainer:
      'Descreva seu problema e informe um telefone para contato. Nossa equipe retornará fora do app em até 2 dias úteis.',
    phonePlaceholder: '(11) 99999-9999',
    phoneLabel: 'Telefone',
    messagePlaceholder: 'Descreva o problema ou dúvida…',
    messageLabel: 'Mensagem',
    messageHint: 'Não compartilhe senhas, documentos ou dados de pagamento.',
    attachImage: 'Adicionar imagem (opcional)',
    imageAttached: 'Imagem anexada',
    removeImage: 'Remover imagem',
    submit: 'Enviar',
    submitting: 'Enviando…',
    submitted: 'Chamado enviado! Retornaremos pelo telefone informado.',
    submitFailed: 'Não foi possível enviar. Tente novamente.',
    loadFailed: 'Não foi possível carregar seus chamados.',
    openTicketsTitle: 'Chamados abertos',
    noOpenTickets: 'Você não tem chamados em aberto.',
    ticketCreatedOn: 'Enviado em',
    phoneRequired: 'Informe o telefone.',
    messageRequired: 'Informe a mensagem.',
  },
  errors: {
    network: 'Sem conexão. Tente novamente.',
    unknown: 'Algo deu errado.',
    imageTooLarge: 'Imagem acima de 10 MB.',
    imagePicker: 'Não foi possível abrir a galeria.',
  },
};
