export const profileCopy = {
  profile: {
    title: 'Perfil',
    edit: 'Editar',
    editDetails: 'Editar dados',
    save: 'Salvar',
    cancel: 'Cancelar',
    nameLabel: 'Nome',
    bioLabel: 'Bio',
    cityLabel: 'Cidade',
    stateLabel: 'Estado (UF)',
    avatarChange: 'Alterar foto',
    avatarUploading: 'Enviando foto…',
    saved: 'Perfil atualizado.',
    saveFailed: 'Não foi possível salvar.',
    loadFailed: 'Não foi possível carregar o perfil.',
  },
  menu: {
    subtitle: 'Gerencie seus dados, endereços e sua garagem.',
    editHint: 'Atualize nome, bio e localização',
    orders: 'Meus pedidos',
    ordersHint: 'Acompanhe compras da loja e pedidos mistos',
    shipping: 'Endereços',
    shippingHint: 'Cadastre e edite seus endereços de entrega',
    garage: 'Garagem',
    garageHint: 'Veja e edite seus carros',
    logoutHint: 'Encerrar sessão neste aparelho',
  },
  shipping: {
    title: 'Endereços',
    newTitle: 'Novo endereço',
    empty: 'Você ainda não cadastrou endereços de entrega.',
    add: 'Adicionar endereço',
    retry: 'Tentar novamente',
    recipientNameLabel: 'Nome do destinatário',
    phoneLabel: 'Telefone',
    postalCodeLabel: 'CEP',
    streetLabel: 'Rua',
    numberLabel: 'Número',
    complementLabel: 'Complemento (opcional)',
    neighborhoodLabel: 'Bairro',
    cityLabel: 'Cidade',
    stateCodeLabel: 'Estado (UF)',
    cepLookupNotFound: 'CEP não encontrado. Preencha o endereço manualmente.',
    cepLookupError: 'Erro ao buscar CEP. Verifique sua conexão.',
    defaultLabel: 'Usar como endereço padrão',
    defaultBadge: 'Padrão',
    save: 'Salvar',
    saved: 'Endereço atualizado.',
    saveFailed: 'Não foi possível salvar o endereço.',
    loadFailed: 'Não foi possível carregar os endereços.',
    delete: 'Excluir',
    deleteConfirm: 'Remover este endereço?',
  },
  garage: {
    title: 'Garagem',
    newTitle: 'Novo Carro',
    empty: 'Você ainda não cadastrou carros.',
    add: 'Adicionar carro',
    makeLabel: 'Marca',
    modelLabel: 'Modelo',
    yearLabel: 'Ano',
    nicknameLabel: 'Apelido (opcional)',
    save: 'Salvar',
    saved: 'Carro atualizado.',
    saveFailed: 'Não foi possível salvar o carro.',
    delete: 'Excluir',
    deleteConfirm: 'Remover este carro?',
    addPhoto: 'Adicionar foto',
    replacePhoto: 'Trocar',
    photoUploading: 'Enviando foto…',
    removePhoto: 'Remover',
    removePhotoConfirm: 'Remover foto deste carro?',
  },
  errors: {
    network: 'Sem conexão. Tente novamente.',
    unknown: 'Algo deu errado.',
    imageTooLarge: 'Imagem acima de 10 MB.',
    imagePicker: 'Não foi possível abrir a galeria.',
  },
};
