export const ticketsCopy = {
  tab: 'Ingressos',
  list: {
    empty: 'Você ainda não tem ingressos.',
    emptyFilter: 'Nenhum ingresso nesta categoria.',
    loading: 'Carregando seus ingressos...',
    upcoming: 'Próximos',
    past: 'Anteriores',
    pendingExtras: 'Extras não utilizados',
    pendingExtrasOne: 'Extra não utilizado',
  },
  filters: {
    all: 'Todos',
    valid: 'Válidos',
    used: 'Utilizados',
    expired: 'Expirados',
    event: 'Evento:',
    eventClear: 'Limpar filtro de evento',
  },
  detail: {
    title: 'Seu ingresso',
    brightness: 'Aumente o brilho da tela para o QR ser lido com facilidade.',
    used: 'Utilizado',
    revoked: 'Cancelado',
    valid: 'Válido',
    notFound: 'Ingresso não encontrado.',
    extrasTitle: 'Extras',
    qrUsed: 'QrCode Utilizado',
    nicknameLabel: 'Nome do ingresso',
    nicknamePlaceholder: 'Ex.: João, Maria',
    nicknameEdit: 'Editar nome',
    nicknameAdd: 'Adicionar nome',
    nicknameSave: 'Salvar',
    nicknameCancel: 'Cancelar',
    nicknameRemove: 'Remover',
    nicknameSaving: 'Salvando...',
    nicknameError: 'Não foi possível salvar. Tente novamente.',
    nicknameMaxLengthHint: 'Até 60 caracteres.',
    pickupTitle: 'Retiradas no evento',
    pickupHelp: 'Apresente o QR Code deste ingresso na loja do evento para retirar os itens.',
    pickupOrderLabel: (shortId: string) => `Pedido #${shortId}`,
    pickupStatus: {
      unfulfilled: 'Aguardando retirada',
      pickup_ready: 'Pronto para retirar',
      picked_up: 'Retirado',
      cancelled: 'Cancelado',
    },
    pickupItemQuantity: (quantity: number) => `${quantity} un.`,
  },
  purchase: {
    pickTier: 'Escolha um ingresso',
    confirm: 'Confirmar compra',
    paying: 'Processando pagamento...',
    success: 'Ingresso confirmado!',
    successCta: 'Ver ingresso',
    soldOut: 'Esgotado',
    alreadyHas: 'Você já tem um ingresso para este evento.',
    error: 'Não conseguimos concluir seu pagamento. Tente novamente.',
    cancelled: 'Pagamento cancelado.',
  },
};
